"""add chunk embeddings

Revision ID: 97812f40e603
Revises: c966ce9bb3d7
Create Date: 2026-09-25 14:33:25.259798

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '97812f40e603'
down_revision: Union[str, Sequence[str], None] = 'c966ce9bb3d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chunks",
        sa.Column(
            "embedding",
            Vector(384),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chunks", "embedding")
    # ### end Alembic commands ###