"""add document and chunk constraints

Revision ID: c966ce9bb3d7
Revises: 11c69a711736
Create Date: 2026-09-24 14:46:42.753298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c966ce9bb3d7'
down_revision: Union[str, Sequence[str], None] = '11c69a711736'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_chunk_position', 'chunks', ['document_version_id', 'chunk_index'])
    op.create_index(op.f('ix_document_versions_is_current'), 'document_versions', ['is_current'], unique=False)
    op.create_unique_constraint('uq_document_version_number', 'document_versions', ['document_id', 'version_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_document_version_number', 'document_versions', type_='unique')
    op.drop_index(op.f('ix_document_versions_is_current'), table_name='document_versions')
    op.drop_constraint('uq_chunk_position', 'chunks', type_='unique')
    # ### end Alembic commands ###
